### ISSUE TITLE
cannot use character to kill monster created by spawn

### ISSUE THREAD

**Issue by Rushyoung** [snoobi-seggs/nahida_seggs#2]
THANK YOU FOR YOUR GREAT WORK!
while i play the game,i found the character cannot kill those monsters created by the private server.it seems that only those created "naturally" can be killed,and all characters' HP were be locked to 100000.how could i solve this problem ？

BTW,i got a file called "[ConfigAbility_Monster_Nada.bin](https://nite07-my.sharepoint.com/:u:/p/rushyoung233/EejnPNdDA4ZAkFGu49W3IfYBuCqtYG-w8nEpPaIuV0il4A?e=RiJYOp)",it seems to be used for Scaramouche,but i donnot konw how to use it,if u ca n help me i would appreciate u much.

pls forgive my poor english

**Comment by snoobi-seggs** [comment]
the 100khp and never dying enemies is set by me coz its f u n

nada is scara and client issue for .50 so even with it it wont work. yes i alr have the json i just didnt push it coz of KIRA U FUCKING ASSHOLE understand?

**Comment by Rushyoung** [comment]
well,i got it.thank u for your answer
